# Generated by Django 4.2.6 on 2023-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='info@mahisagarpackersandmovers.com', max_length=254),
        ),
    ]
