# Generated by Django 4.2.6 on 2023-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_alter_branch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='category',
            field=models.CharField(blank=True, default='Branch Office', max_length=50, null=True),
        ),
    ]
