# Generated by Django 4.2.6 on 2023-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('s_from', models.CharField(max_length=50)),
                ('s_to', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
