# Generated by Django 4.2.6 on 2023-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_alter_branch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Mahisagar Packers and Movers', max_length=100, unique=True),
        ),
    ]
