# Generated by Django 4.2.6 on 2023-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_quote_alter_pages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
