# Generated by Django 4.2.6 on 2023-10-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_branch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
