# Generated by Django 4.2.6 on 2023-10-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_quote_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
