# Generated by Django 4.2.6 on 2023-10-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_alter_quote_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
