# Generated by Django 4.2.6 on 2023-10-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_alter_branch_mobile_alter_quote_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
